---
- name: Install RKE2 Agent on GPU Node
  hosts: gpu_nodes
  become: yes
  gather_facts: yes
  vars:
    rke2_server_ip: "10.0.1.4"  # Private IP of rancher server
    rke2_token: "K10333f179959a1e3c91427e8633ac8cadd4069b37533d82e55a5eb3207910e730c::server:4ebc8b6a04118c0fd5d7d5f93aca399b"
  tasks:
    - name: Create RKE2 config directory
      file:
        path: /etc/rancher/rke2
        state: directory
        mode: '0755'

    - name: Create RKE2 agent configuration
      copy:
        content: |
          server: https://{{ rke2_server_ip }}:9345
          token: {{ rke2_token }}
          node-label:
            - "node-type=gpu"
            - "nvidia.com/gpu=true"
        dest: /etc/rancher/rke2/config.yaml
        mode: '0600'

    - name: Download RKE2 installation script
      get_url:
        url: https://get.rke2.io
        dest: /tmp/install-rke2.sh
        mode: '0755'

    - name: Install RKE2 agent
      shell: |
        INSTALL_RKE2_TYPE="agent" /tmp/install-rke2.sh
      args:
        creates: /usr/local/bin/rke2-agent

    - name: Enable and start rke2-agent service
      systemd:
        name: rke2-agent
        enabled: yes
        state: started

    - name: Wait for RKE2 agent to be ready
      wait_for:
        port: 10250
        host: "{{ ansible_default_ipv4.address }}"
        timeout: 300
        delay: 30

    - name: Create kubectl symlink
      file:
        src: /var/lib/rancher/rke2/bin/kubectl
        dest: /usr/local/bin/kubectl
        state: link
      ignore_errors: yes

    - name: Verify RKE2 agent installation
      shell: |
        systemctl is-active rke2-agent
      register: rke2_agent_status
      changed_when: false

    - name: Display RKE2 agent status
      debug:
        msg: "RKE2 agent status: {{ rke2_agent_status.stdout }}"
